### ISSUE TITLE
I have question

### ISSUE THREAD

**Issue by Andriuxas** [Mikooboy/csgo-chat-bot_2.0#2]
Can't you just get banned while using it?

**Comment by Mikooboy** [comment]
Technically it's against the CSGO rules to automate anything. However this will not get you VAC banned since it only communicates with CSGO through the netconport which is implemented by valve.

It's pretty much the same as with macros. They are against the rules but no one is getting banned for using them.

**Comment by Andriuxas** [comment]
What modules I have to install tho?

**Comment by Mikooboy** [comment]
Most of the used modules already come with a python install.
If you try to run the program it should tell you which modules are not installed.

**Comment by Andriuxas** [comment]
Is it possible to activate those commands somewhere else. I mean not writing in the chat. Maybe on console?
